[Display]
# Skyrim_VEV-P.ini - parametri luce e bloom ottimizzati
fGlobalBloomThresholdBoost=0.30
fSunShadowUpdateTime=0.25
fSunUpdateThreshold=2.0
fLightLODMaxStartFade=4200.0
fLightLODStartFade=4200.0
